name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: docker login
      uses: actions/docker/ashok@v2
      with:
        username: ashok2421
        password: dckr_pat_nrzCH5qs8jTNj2Pfp2iU0I3_9J8
    - name: tagdockerimage
      run: docker my-image-name:$(date +%s) ashok2421/maven-web-application:$(date +%s)
    - name: docker push
      run: docker image push ashok2421/maven-web-application:$(date +%s)
